# Generated by Django 2.1 on 2018-09-29 05:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('pending_loan', models.IntegerField(default=0)),
                ('member_debt', models.PositiveIntegerField(default=0)),
                ('member_capital', models.PositiveIntegerField(default=0)),
                ('member_share', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='company_files/docs/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'archives',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(default='addCompanyName', max_length=50)),
                ('Company_slogan', models.CharField(default='addCompanySlogan', max_length=50)),
                ('Company_logo', models.ImageField(default='media/no-image.jpg', upload_to='company_files/logo')),
                ('Number_of_members', models.PositiveSmallIntegerField(default=4)),
                ('Balance_BF', models.PositiveIntegerField(default=0)),
                ('total_debts', models.PositiveIntegerField(default=0)),
                ('Company_value', models.PositiveIntegerField(default=0)),
                ('general_share', models.PositiveIntegerField(default=0)),
                ('Liquid_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxLoan', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('loan_amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(7000000)])),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('interest', models.PositiveIntegerField()),
                ('approved', models.BooleanField(null=True)),
                ('monthly_installment', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Account')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ImageField(upload_to='receipts/%Y/%m/%d/')),
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('LP', 'Loan_repayment'), ('GT', 'Grant'), ('SP', 'Subscription')], default='notSet', max_length=20)),
                ('payment_amount', models.PositiveIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Company')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
