# Generated by Django 2.1 on 2018-09-29 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_auto_20180929_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(null=True)),
                ('loan_application', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Company')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Loan')),
            ],
        ),
    ]
