# Generated by Django 2.1 on 2018-09-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_approveloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='name',
            field=models.CharField(default='no name', max_length=50),
        ),
    ]
