# Generated by Django 2.1 on 2018-09-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_loan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='approved',
            field=models.CharField(choices=[('AP', 'Approved'), ('RJ', 'Rejected'), ('IR', 'In-Review')], default='select', max_length=20),
        ),
    ]
