# Generated by Django 2.1 on 2018-09-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_auto_20180930_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='approveloan',
            name='decision',
            field=models.CharField(default='In_Review', max_length=20),
        ),
        migrations.AlterField(
            model_name='approveloan',
            name='remarks',
            field=models.TextField(default='Add comments'),
        ),
    ]
