# Generated by Django 2.1 on 2018-10-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_auto_20181007_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='member_loan',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='member_share',
            field=models.IntegerField(default=0),
        ),
    ]
