# Generated by Django 2.1.3 on 2018-11-21 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0011_account_member_total_debts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('count', models.PositiveIntegerField()),
                ('bill_amount', models.PositiveIntegerField(default=0)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='approveloan',
            name='status',
            field=models.CharField(choices=[('IR', 'In-Review'), ('AP', 'Approved'), ('RJ', 'Rejected'), ('CR', 'Cleared')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
