# Generated by Django 2.1.3 on 2019-04-06 05:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0015_auto_20190106_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='site_video',
            field=cloudinary.models.CloudinaryField(default='media/uploads/video.mp4', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='Company_logo',
            field=cloudinary.models.CloudinaryField(default='media/uploads/image.png', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=cloudinary.models.CloudinaryField(default='media/uploads/image.png', max_length=255, verbose_name='image'),
        ),
    ]
