# Generated by Django 2.1.3 on 2019-04-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0016_auto_20190406_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='site_video',
        ),
    ]
